version: '3.1'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    # Uncomment if you want data to persist on device
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_backups/${DOCKER_BACKUP_FILE}:/docker-entrypoint-initdb.d/ticketio_prod.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: on-failure

volumes:
  postgres-data:
